import express from 'express';
import { activateUser, deleteUser, getUserInfo, loginUser, logoutUser, registrationUser, socialAuth, UpdateAccesstoken, updateInfo, updatePassword, updateProfilepic, updateUserRole } from '../controllers/user.controller';
import { isAuth, ValidateUserRole } from '../middleware/isAuth';
import { getAllUsers } from '../services/user.service';

const userRouter = express.Router();
userRouter.post('/register', registrationUser);
userRouter.post('/activateuser', activateUser);
userRouter.post('/login', loginUser);
userRouter.get('/logout',isAuth, logoutUser);
userRouter.get('/refreshtoken',UpdateAccesstoken);
userRouter.get('/getuserinfo',isAuth,getUserInfo);
userRouter.post('/social',socialAuth);
userRouter.put('/updateuser' , isAuth , updateInfo);
userRouter.put('/updateUser' , isAuth ,ValidateUserRole("admin"), updateUserRole);
userRouter.put('/updatepassword' , isAuth , updatePassword);
userRouter.put('/updateprofilepic' , isAuth , updateProfilepic);
userRouter.get('/getall' , isAuth ,ValidateUserRole("admin"), getAllUsers);
userRouter.delete('/deleteuser/:id' , isAuth ,ValidateUserRole("admin"), deleteUser);
export default userRouter;
