"use client";


//------------------------------- TAKE REFERENCE BECAUSE GENERATED BY AI --------------------------



import React, { FC } from "react";
import Image from "next/image";
import { IoSearch } from "react-icons/io5";

interface HeroProps {}

const Hero: FC<HeroProps> = () => {
  return (
    <section className="w-full h-[calc(100vh-80px)] flex flex-col md:flex-row items-center justify-between px-6 md:px-20 py-12 bg-gray-900 text-white">
      {/* Left side - Illustration */}
      <div className="w-full md:w-1/2 flex justify-center md:justify-start mb-10 md:mb-0">
        <div className="relative w-[300px] h-[400px] md:w-[400px] md:h-[500px]">
          <Image
            src="/Hero/2381908.jpg"
            alt="Hero Illustration"
            fill
            style={{ objectFit: "contain", borderRadius: "50%" }}
          />
        </div>
      </div>

      {/* Right side - Content */}
      <div className="w-full md:w-1/2 flex flex-col gap-6">
        <h1 className="text-4xl md:text-5xl font-bold leading-snug">
          Improve Your Online <br /> Learning Experience <br /> Better Instantly
        </h1>
        <p className="text-sm md:text-base text-gray-300">
          We have 40k+ Online courses & 500K+ Online registered students. Find
          your desired courses from them.
        </p>

        {/* Search Bar */}
        <div className="flex rounded-md w-full max-w-md mt-4">
          <input
            type="text"
            placeholder="Search Courses..."
            className="flex-1 p-3 rounded-l-md text-white bg-gray-500 focus:outline-none"
          />
          <button className="bg-sky-700 px-4 rounded-r-md hover:bg-sky-600 transition">
            <IoSearch />
          </button>
        </div>

        {/* Trusted Users */}
        <div className="flex items-center gap-2 mt-4">
          <div className="flex w-fit -space-x-2">
            <Image
              src="/Hero/user/62424a3e-9cdc-422f-a2c8-5cce272934e2.jpg"
              alt="User"
              width={27}
              height={10}
              className="rounded-full border-2"
            />
            <Image
              src="/Hero/user/bc9fd4bd-de9b-4555-976c-8360576c6708.jpg"
              alt="User"
              width={27}
              height={10}
              className="rounded-full border-2"
            />
            <Image
              src="/Hero/user/e4246d0c-bef9-4c10-a903-d45344428107.jpg"
              alt="User"
              width={27}
              height={10}
              className="rounded-full border-2"
            />
          </div>
          <p className="text-gray-300 text-sm">
            500K+ People already trusted us.{" "}
            <span className="text-green-500 cursor-pointer hover:underline">
              View Courses
            </span>
          </p>
        </div>
      </div>
    </section>
  );
};

export default Hero;
